/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package projectui;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Logger;
import java.util.logging.Level;


/**
 *
 * @author Lenovo
 */
public class FormPenjualan extends javax.swing.JFrame {
    int idTerpilih = 0;
    private Statement St;
    private Connection Con;
    private ResultSet Rs;
    private String sql="";
    DefaultTableModel model;
    String[] selectedOldData = new String [10];
    

    
double harusdibayar;
    /**
     * Creates new form FormPenjualan
     */                                                                 
    public FormPenjualan() {
        initComponents(); 
        KoneksiDatabase();
        loadDataToTable();                                  
    }
    
    private void KoneksiDatabase () {
        try {
            
            
            //menentukan driver data base
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            //untuk mengkoneksikan database ke driver
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3307/db_biodata","root", "");
            
            //pesan koneksi berhasil
            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        } catch (Exception e) {
            //pesan koneksi gagal
            System.out.println("koneksi gagal" + e.getMessage());
        }
    }
    
    // Method untuk membersihkan semua field input
private void clearForm() {
    txtnama.setText("");
    cmbPaketMakanan.setSelectedIndex(0); // Pilih item pertama di combo box
    txtMenuMakanan.setText("");
    txtHarga.setText("");
    txtJumlah.setText("");
    txtTotalBelanja.setText("");
    txtDiskon.setText("");
    txtHarusdiBayar.setText("");
    txtJumlahBayar.setText("");
    txtkembali.setText("");
}

    private void loadDataToTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Hapus data lama

    try {
        String sql = "SELECT * FROM db_penjualan";
        Statement stmt = Con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"), // ID sebagai kolom pertama
                rs.getString("Nama"),
                rs.getString("Paket_Makanan"),
                rs.getString("Menu_Makanan"),
                rs.getInt("Harga"),
                rs.getInt("Jumlah"),
                rs.getInt("Total_Belanja"),
                rs.getDouble("Diskon"),
                rs.getDouble("Harus_Dibayar"),
                rs.getInt("Jumlah_Bayar"),
                rs.getDouble("Kembalian")
            });
        }

        // Sembunyikan kolom ID (kolom 0)
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data: " + e.getMessage());
    }
}


 public void reset() {
        txtnama.setText(null);
        cmbPaketMakanan.requestFocus();
        txtMenuMakanan.setText(null);
        txtHarga.setText(null);
        txtJumlah.setText(null);
        txtTotalBelanja.setText(null);
        txtDiskon.setText(null);
        txtHarusdiBayar.setText(null);
        txtJumlahBayar.setText(null);
        txtkembali.setText(null);
    }                            


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbPaketMakanan = new javax.swing.JComboBox<>();
        txtMenuMakanan = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotalBelanja = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtHarusdiBayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtJumlahBayar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtkembali = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KHOIRUL INSANUL HAMDI");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PENJUALAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WARUNG HAMDI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 100, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jumlah");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 80, 26));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Belanja");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 83, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Diskon");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 83, -1));

        cmbPaketMakanan.setBackground(new java.awt.Color(204, 204, 204));
        cmbPaketMakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Paket", "JASMINE", "ASOKA", "EDELWEIS", "", "" }));
        cmbPaketMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaketMakananActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPaketMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));
        getContentPane().add(txtMenuMakanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 89, -1));
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 89, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 68, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 78, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Paket Makanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu Makanan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 130, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Harus di Bayar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 83, -1));
        getContentPane().add(txtTotalBelanja, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 106, -1));

        txtDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiskonActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 106, -1));
        getContentPane().add(txtHarusdiBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 260, 106, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jumlah Bayar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 83, -1));

        txtJumlahBayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJumlahBayarFocusLost(evt);
            }
        });
        txtJumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBayarActionPerformed(evt);
            }
        });
        getContentPane().add(txtJumlahBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, 106, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembalian");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 83, -1));
        getContentPane().add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, 106, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton2.setText("ULANG TRANSAKSI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, 44));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        jButton3.setText("KELUAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 400, 100, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Paket_Makanan", "Menu_Makanan", "Harga", "Jumlah", "Total_Belanja", "Diskon", "Harus_Dibayar", "Jumlah_Bayar", "Kembalian"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 1270, 260));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton4.setText("SIMPAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 124, 44));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 89, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton5.setText("HAPUS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 100, 44));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        jButton6.setText("EDIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 100, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wait.png"))); // NOI18N
        jButton7.setText("REFRESH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 44));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, 80, -1));

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, 110, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
        jLabel13.setText("j");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPaketMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaketMakananActionPerformed
       if (cmbPaketMakanan.getSelectedItem().equals("JASMINE")){
           txtMenuMakanan.setText("Katsu");
           txtHarga.setText("15000");
           txtJumlah.requestFocus();
       }
       else if (cmbPaketMakanan.getSelectedItem().equals("ASOKA")){
           txtMenuMakanan.setText("ayampenyet");
           txtHarga.setText("17000");
           txtJumlah.requestFocus();
       }
       else{
           txtMenuMakanan.setText("NasiKulit");
           txtHarga.setText("20000");
           txtJumlah.requestFocus();
       }
    }//GEN-LAST:event_cmbPaketMakananActionPerformed

    private void txtDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiskonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiskonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int jumlah;
        int harga;
        int totalbelanja;
        double diskon;
        
        jumlah=Integer.parseInt(txtJumlah.getText());
        harga=Integer.parseInt(txtHarga.getText());
        totalbelanja=jumlah*harga;
        txtTotalBelanja.setText(Integer.toString(totalbelanja));
        
        if (jumlah>=2){
            diskon=0.1*totalbelanja;
            txtDiskon.setText(Double.toString(diskon));
            harusdibayar=totalbelanja-diskon;
            txtHarusdiBayar.setText(Double.toString(harusdibayar));
            txtJumlahBayar.requestFocus();
        }
        else{
            diskon=0*totalbelanja;
            txtDiskon.setText(Double.toString(diskon));
            harusdibayar=totalbelanja-diskon;
            txtHarusdiBayar.setText(Double.toString(harusdibayar));
            txtJumlahBayar.requestFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtJumlahBayarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahBayarFocusLost
       double kembali;
       double bayar;
       
       bayar=Double.parseDouble(txtJumlahBayar.getText());
       kembali=bayar-harusdibayar;
       txtkembali.setText(Double.toString(kembali));
    }//GEN-LAST:event_txtJumlahBayarFocusLost

    private void txtJumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBayarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtnama.setText(null);
        cmbPaketMakanan.requestFocus();
        txtMenuMakanan.setText(null);
        txtHarga.setText(null);
        txtJumlah.setText(null);
        txtTotalBelanja.setText(null);
        txtDiskon.setText(null);
        txtHarusdiBayar.setText(null);
        txtJumlahBayar.setText(null);
        txtkembali.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

// Validasi input
if (txtnama.getText().trim().equals("")
        || cmbPaketMakanan.getSelectedItem().toString().trim().equals("")
        || txtMenuMakanan.getText().trim().equals("")
        || txtHarga.getText().trim().equals("")
        || txtJumlah.getText().trim().equals("")
        || txtTotalBelanja.getText().trim().equals("")
        || txtDiskon.getText().trim().equals("")
        || txtHarusdiBayar.getText().trim().equals("")
        || txtJumlahBayar.getText().trim().equals("")
        || txtkembali.getText().trim().equals("")) {

    JOptionPane.showMessageDialog(null, "Data belum lengkap!");
    return;
}

// Tambah data ke Tabel GUI
model.addRow(new Object[]{
    
    txtnama.getText(),
    cmbPaketMakanan.getSelectedItem().toString(),
    txtMenuMakanan.getText(),
    txtHarga.getText(),
    txtJumlah.getText(),
    txtTotalBelanja.getText(),
    txtDiskon.getText(),
    txtHarusdiBayar.getText(),
    txtJumlahBayar.getText(),
    txtkembali.getText()
});

// ✅ Tambah SQL INSERT (bukan update)
String sql = "INSERT INTO db_penjualan (Nama, Paket_Makanan, Menu_Makanan, Harga, Jumlah, Total_Belanja, Diskon, Harus_Dibayar, Jumlah_Bayar, Kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

try (Connection conn = KoneksiDB.getConnection();
     PreparedStatement pst = conn.prepareStatement(sql)) {

    pst.setString(1, txtnama.getText());
    pst.setString(2, cmbPaketMakanan.getSelectedItem().toString());
    pst.setString(3, txtMenuMakanan.getText());
    pst.setInt(4, Integer.parseInt(txtHarga.getText()));
    pst.setInt(5, Integer.parseInt(txtJumlah.getText()));
    pst.setInt(6, Integer.parseInt(txtTotalBelanja.getText()));
    pst.setDouble(7, Double.parseDouble(txtDiskon.getText()));
    pst.setDouble(8, Double.parseDouble(txtHarusdiBayar.getText()));
    pst.setInt(9, Integer.parseInt(txtJumlahBayar.getText()));
    pst.setDouble(10, Double.parseDouble(txtkembali.getText()));

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");

    loadDataToTable(); // Refresh tabel
    clearForm();       // Kosongkan form

} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Simpan gagal: " + e.getMessage());
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int row = jTable1.getSelectedRow();

if (row == -1) {
    JOptionPane.showMessageDialog(null, "Pilih data yang mau dihapus!");
    return;
}

int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

try {
    Connection conn = KoneksiDB.getConnection();
    String sql = "DELETE FROM db_penjualan WHERE id=?";
    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setInt(1, id);

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");

    loadDataToTable(); // refresh tabel
    reset(); // kosongkan form

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal hapus: " + e.getMessage());
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       if (txtnama.getText().trim().isEmpty() 
    || cmbPaketMakanan.getSelectedItem().toString().trim().isEmpty()
    || txtMenuMakanan.getText().trim().isEmpty()
    || txtHarga.getText().trim().isEmpty()
    || txtJumlah.getText().trim().isEmpty()
    || txtTotalBelanja.getText().trim().isEmpty()
    || txtDiskon.getText().trim().isEmpty()
    || txtHarusdiBayar.getText().trim().isEmpty()
    || txtJumlahBayar.getText().trim().isEmpty()
    || txtkembali.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(null, "Data belum lengkap!");
    return;
}

if (idTerpilih == 0) {
    JOptionPane.showMessageDialog(null, "Pilih data di tabel dulu!");
    return;
}

try {
    Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3307/db_biodata", "root", "");

    String sql = "UPDATE db_penjualan SET nama=?, Paket_Makanan=?, Menu_Makanan=?, Harga=?, Jumlah=?, Total_Belanja=?, Diskon=?, Harus_Dibayar=?, Jumlah_Bayar=?, Kembalian=? WHERE id=?";
    PreparedStatement pst = cn.prepareStatement(sql);

    pst.setString(1, txtnama.getText());
    pst.setString(2, cmbPaketMakanan.getSelectedItem().toString());
    pst.setString(3, txtMenuMakanan.getText());

    pst.setInt(4, (int) Double.parseDouble(txtHarga.getText()));
    pst.setInt(5, (int) Double.parseDouble(txtJumlah.getText()));
    pst.setInt(6, (int) Double.parseDouble(txtTotalBelanja.getText()));
    pst.setInt(7, (int) Double.parseDouble(txtDiskon.getText()));
    pst.setInt(8, (int) Double.parseDouble(txtHarusdiBayar.getText()));
    pst.setInt(9, (int) Double.parseDouble(txtJumlahBayar.getText()));
    pst.setInt(10, (int) Double.parseDouble(txtkembali.getText()));

    pst.setInt(11, idTerpilih);

    int rows = pst.executeUpdate();

    if (rows > 0) {
        JOptionPane.showMessageDialog(null, "Data berhasil diupdate!");
        loadDataToTable();
        reset();
        idTerpilih = 0; // reset id
    } else {
        JOptionPane.showMessageDialog(null, "Update gagal!");
    }

} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        if (i > -1) {
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for (int j = 0; j < 10; j++) {
                selectedOldData[j] = model.getValueAt(i, j).toString();
            }

            txtnama.setText(selectedOldData[0]);
            cmbPaketMakanan.setSelectedItem(selectedOldData[1]);
            txtMenuMakanan.setText(selectedOldData[2]);
            txtHarga.setText(selectedOldData[3]);
            txtJumlah.setText(selectedOldData[4]);
            txtTotalBelanja.setText(selectedOldData[5]);
            txtDiskon.setText(selectedOldData[6]);
            txtHarusdiBayar.setText(selectedOldData[7]);
            txtJumlahBayar.setText(selectedOldData[8]);
            txtkembali.setText(selectedOldData[9]);
        }
 
    
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       loadDataToTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    try {
        Statement st = Con.createStatement();
        ResultSet rs = st.executeQuery(
            "SELECT * FROM db_penjualan WHERE nama LIKE '%" + txtsearch.getText() + "%'"
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id"), // WAJIB di index pertama
                rs.getString("nama"),
                rs.getString("paket_makanan"),
                rs.getString("menu_makanan"),
                rs.getInt("harga"),
                rs.getInt("jumlah"),
                rs.getInt("total_belanja"),
                rs.getDouble("diskon"),
                rs.getDouble("harus_dibayar"),
                rs.getDouble("jumlah_bayar"),
                rs.getDouble("kembalian")
            });
        }

    } catch (Exception e) {
        System.out.println(e);
    }
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cmbPaketMakanan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHarusdiBayar;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtJumlahBayar;
    private javax.swing.JTextField txtMenuMakanan;
    private javax.swing.JTextField txtTotalBelanja;
    private javax.swing.JTextField txtkembali;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
